<?php
if (!defined('ABSPATH')) { exit; }
mentra_vn_document_open('mentra-os');
mentra_vn_render_partial('site-header');
?>
<main id="main">
<section class="product-page-hero section section-black"><div class="container split align-center"><div class="reveal"><p class="eyebrow">MENTRAOS</p><h1 class="product-title">Nền tảng mở cho kính thông minh.</h1><p class="lead">MentraOS mang hệ sinh thái ứng dụng, SDK dành cho nhà phát triển và trải nghiệm thống nhất lên nhiều mẫu kính thông minh — với mã nguồn mở.</p><div class="button-row"><a class="btn btn-light" href="https://docs.mentraglass.com" target="_blank" rel="noopener">Xem tài liệu ↗</a><a class="btn btn-outline-light" href="https://github.com/Mentra-Community" target="_blank" rel="noopener">GitHub ↗</a></div></div><div class="phone-stage reveal"><img src="<?php echo mentra_vn_asset('Mockup_OS_Phone_Hand.png'); ?>" alt="MentraOS"></div></div></section>
<section class="section"><div class="container"><div class="section-heading reveal"><p class="eyebrow">HỆ SINH THÁI</p><h2>Một ứng dụng, nhiều loại kính tương thích.</h2><p>Xây dựng MiniApp và cung cấp trải nghiệm nhất quán trên các phần cứng được MentraOS hỗ trợ.</p></div><div class="cards-3"><article class="feature-card reveal"><img src="<?php echo mentra_vn_asset('mentra_live_compare.webp'); ?>" alt="Mentra Live"><h3>Mentra Live</h3><p>Được hỗ trợ.</p></article><article class="feature-card reveal"><img src="<?php echo mentra_vn_asset('even_g1_sexy_1.png'); ?>" alt="Even Realities"><h3>Even Realities</h3><p>Thiết bị tương thích trong hệ sinh thái MentraOS.</p></article><article class="feature-card reveal"><img src="<?php echo mentra_vn_asset('VuzixZ100.png'); ?>" alt="Vuzix Z100"><h3>Vuzix Z100</h3><p>Thiết bị tương thích trong hệ sinh thái.</p></article></div></div></section>
<section class="section section-soft"><div class="container split align-center"><div class="reveal"><p class="eyebrow">MINIAPP</p><h2>Mang ứng dụng trực tiếp lên kính.</h2><p>Caption, camera, ghi chú, dịch thuật và các ứng dụng do cộng đồng phát triển có thể được khám phá và cài đặt từ Mentra Miniapp Store.</p><a class="btn btn-dark" href="https://apps.mentraglass.com" target="_blank" rel="noopener">Khám phá Miniapp Store ↗</a></div><img class="reveal" src="<?php echo mentra_vn_asset('Mentra_MiniApp_Store_on_iPhone_Jan2026.png'); ?>" alt="Mentra Miniapp Store"></div></section>
<section class="section section-green"><div class="container narrow reveal"><p class="eyebrow">SDK</p><h2>Xây dựng ứng dụng kính thông minh trong vài phút, không phải vài tháng.</h2><p>Dùng công cụ dành cho nhà phát triển để đăng ký MiniApp, cấu hình dự án và bắt đầu tích hợp bằng SDK.</p><div class="button-row"><a class="btn btn-dark" href="https://console.mentraglass.com" target="_blank" rel="noopener">Developer Console ↗</a><a class="btn btn-outline" href="https://docs.mentraglass.com" target="_blank" rel="noopener">Tài liệu ↗</a></div></div></section>
</main>
<?php
mentra_vn_render_partial('site-footer');
mentra_vn_document_close();
